import { getPool, isConfigured } from '../db/pool.js';
export class BeliefClaimError extends Error { constructor(message) { super(message); this.name='BeliefClaimError'; } }
const required=(v,n)=>{if(v===undefined||v===null||v==='') throw new BeliefClaimError(`${n} is required`); return v;};
const rel=v=>{const r=v??'supporting'; if(!['supporting','contradicting'].includes(r)) throw new BeliefClaimError(`invalid relation: ${r}`); return r;};
const wt=v=>{const n=v==null?1:Number(v); if(!Number.isFinite(n)||n<0||n>1) throw new BeliefClaimError('weight must be between 0 and 1'); return n;};
export async function linkBeliefClaim(i){const ownerId=required(i.ownerId,'ownerId'),beliefId=required(i.beliefId,'beliefId'),dimension=required(i.dimension,'dimension'),beliefKey=required(i.beliefKey,'beliefKey'),claimId=required(i.claimId,'claimId'); if(!isConfigured()) throw new BeliefClaimError('DATABASE_URL is not set'); const p=getPool(); const {rows} = await p.query(`INSERT INTO aqua_belief_claims (owner_id,belief_id,dimension,belief_key,claim_id,relation,weight) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (owner_id,belief_id,claim_id) DO UPDATE SET dimension=EXCLUDED.dimension,belief_key=EXCLUDED.belief_key,relation=EXCLUDED.relation,weight=EXCLUDED.weight,updated_at=now() RETURNING owner_id,belief_id,dimension,belief_key,claim_id,relation,weight,created_at,updated_at`,[ownerId,beliefId,dimension,beliefKey,claimId,rel(i.relation),wt(i.weight)]); return rows[0];}
export async function unlinkBeliefClaim({ownerId,beliefId,claimId}){required(ownerId,'ownerId');required(beliefId,'beliefId');required(claimId,'claimId');if(!isConfigured()) throw new BeliefClaimError('DATABASE_URL is not set');const r=await getPool().query(`DELETE FROM aqua_belief_claims WHERE owner_id=$1 AND belief_id=$2 AND claim_id=$3`,[ownerId,beliefId,claimId]);return r.rowCount>0;}
export async function claimsForBelief({ownerId,beliefId,relation:filterRelation=null}){required(ownerId,'ownerId');required(beliefId,'beliefId');if(!isConfigured())return[];const params=[ownerId,beliefId];const filter=filterRelation==null?'':' AND relation=$3';if(filterRelation!=null)params.push(rel(filterRelation));const {rows}=await getPool().query(`SELECT owner_id,belief_id,dimension,belief_key,claim_id,relation,weight,created_at,updated_at FROM aqua_belief_claims WHERE owner_id=$1 AND belief_id=$2${filter} ORDER BY relation,updated_at DESC,claim_id`,params);return rows;}
export async function beliefsForClaim({ownerId,claimId}){required(ownerId,'ownerId');required(claimId,'claimId');if(!isConfigured())return[];const {rows}=await getPool().query(`SELECT owner_id,belief_id,dimension,belief_key,claim_id,relation,weight,created_at,updated_at FROM aqua_belief_claims WHERE owner_id=$1 AND claim_id=$2 ORDER BY relation,updated_at DESC,belief_id`,[ownerId,claimId]);return rows;}
